### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by peteringram0** [jackfranklin/html-dist#21]
``` console
> html-dist --config html-dist.config-js --input index.html

node_modules/html-dist/src/index.js:1
(function (exports, require, module, __filename, __dirname) { import script from './script';
                                                              ^^^^^^

SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Module._extensions..js (module.js:416:10)
    at Object.require.extensions.(anonymous function) [as .js] (/node_modules/html-dist/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/node_modules/html-dist/bin/cli.js:6:16)
    at Module._compile (module.js:409:26)

```

**Comment by peteringram0** [comment]
@jackfranklin is this plugin still being supported? 👍

**Comment by jackfranklin** [comment]
A little; although I don't have time to work on it properly; I'd like to because I do  think this can be a useful tool!

This issue stems from writing your config file in ES2015. I could never get Babel transpiling it nicely. I would recommend just writing your config in ES5 for now.

**Comment by peteringram0** [comment]
Yer i agree. Do you have an example for this at all? Thanks

**Comment by jackfranklin** [comment]
@peteringram0 as of 0.3.0 this should be fixed, because we no longer parse the config through Babel.

So, if you rewrite your config to whatever is supported by your Node version, this should work now.
